_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.4
            "5": 0.18.7
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
dataset:
    value: kaggle
epochs:
    value: 60
learning_rate:
    value: 0.0003
